//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public int PreferredClassID { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<int> ExtraID { get; set; }
        public double Totalprice { get; set; }
        public double Quantity { get; set; }
    
        public virtual FlightExtra FlightExtra { get; set; }
        public virtual PreferredClass PreferredClass { get; set; }
        public virtual SeatSelection SeatSelection { get; set; }
    }
}
