//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<FlightExtra> FlightExtras { get; set; }
        public virtual DbSet<SeatSelection> SeatSelections { get; set; }
        public virtual DbSet<CreditCard> CreditCards { get; set; }
        public virtual DbSet<InternetPaymentSID> InternetPaymentSIDs { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Flight_Departure> Flight_Departures { get; set; }
        public virtual DbSet<FlightArrival> FlightArrivals { get; set; }
        public virtual DbSet<PreferredClass> PreferredClasses { get; set; }
        public virtual DbSet<FlightTravellerDetail> FlightTravellerDetails { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<FlightBooking> FlightBookings { get; set; }
    }
}
