//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightTravellerDetail
    {
        public int TravellerID { get; set; }
        public int CustomerID { get; set; }
        public string SeatNumber { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Dateofbirth { get; set; }
        public string Gender { get; set; }
        public string Mobilenumber { get; set; }
        public string Email { get; set; }
    
        public virtual SeatSelection SeatSelection { get; set; }
        public virtual User User { get; set; }
    }
}
