//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBooking
    {
        public int FlightID { get; set; }
        public int CustomerID { get; set; }
        public int AirportID { get; set; }
        public Nullable<int> ExtraID { get; set; }
        public string SeatNumber { get; set; }
        public string ReturningDate { get; set; }
        public Nullable<int> NumberOfTravellers { get; set; }
        public double TotalFare { get; set; }
    
        public virtual Flight_Departure Flight_Departure { get; set; }
        public virtual FlightExtra FlightExtra { get; set; }
        public virtual SeatSelection SeatSelection { get; set; }
        public virtual User User { get; set; }
    }
}
