//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetPaymentSID
    {
        public int InternetPaymentID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CardNumber { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
